export const client = Object.freeze({
    GET_CHATS: 'GET_CHATS',
    GET_CHAT_INFO: 'GET_CHAT_INFO',
    NEW_MESSAGE: 'NEW_MESSAGE',
    CREATE_CHAT: 'CREATE_CHAT',
    GET_USER: 'GET_USER',
    SEARCH_USER: 'SEARCH_USER',
    GET_URL_META: 'GET_URL_META',
    CHANGE_AVATAR_URL: 'CHANGE_AVATAR_URL',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    GET_WEATHER: 'GET_WEATHER',
    GET_OR_CREATE_PRIVATE_CHAT: 'GET_OR_CREATE_PRIVATE_CHAT',
    INVITE_WORD: 'INVITE_WORD',
    ADD_REACTION: 'ADD_REACTION',
    REMOVE_REACTION: 'REMOVE_REACTION',
    LEAVE_CHAT: 'LEAVE_CHAT'
});

export const server = Object.freeze({
    LIST_MESSAGES: 'LIST_MESSAGES',
    CHAT: 'CHAT',
    MESSAGE: 'MESSAGE',
    MESSAGE_SENT: 'MESSAGE_SENT',
    MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
    MESSAGE_REVOKED: 'MESSAGE_REVOKED',
    USER: 'USER',
    URL_META: 'URL_META',
    CURRENT_USER: 'CURRENT_USER',
    WEATHER: 'WEATHER',
    USER_LEAVED_CHAT: 'USER_LEAVED_CHAT',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE'
});
