export const client = Object.freeze({
    GET_CHATS: 'GET_CHATS',
    GET_MESSAGES: 'GET_MESSAGES',
    NEW_MESSAGE: 'NEW_MESSAGE',
    GET_USER: 'GET_USER',
    GET_URL_META: 'GET_URL_META',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    GET_WEATHER: 'GET_WEATHER'
});

export const server = Object.freeze({
    LIST_CHATS: 'LIST_CHATS',
    LIST_MESSAGES: 'LIST_MESSAGES',
    MESSAGE: 'MESSAGE',
    USER: 'USER',
    URL_META: 'URL_META',
    CURRENT_USER: 'CURRENT_USER',
    WEATHER: 'WEATHER'
});
