exports.GET_CHATS = 'GET_CHATS';
exports.CHATS_LIST = 'CHATS_LIST';
exports.GET_MESSAGES = 'GET_MESSAGES';
exports.LIST_MESSAGES = 'LIST_MESSAGES';
exports.NEW_MESSAGE = 'NEW_MESSAGE';
exports.MESSAGE = 'MESSAGE';
